# -*- coding: utf-8 -*-
"""Pruebfinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-q5KfMGUxd9BVdaxYOgAWvJ31NzX_1S4
"""

import streamlit as st
import os
from sklearn import metrics
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from openai import OpenAI
from fpdf import FPDF

# Inicializar el cliente de OpenAI
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# Configuración de la página
st.set_page_config(
    page_title="BOT_IA_FINANZAS CARLOS DEVIS",
    page_icon="🧠",
    layout="centered",
    initial_sidebar_state="expanded",
)

# Estilos CSS personalizados
st.markdown(
    """
    <style>
    .main {
        background-color: #E6F0FF;  /* Fondo azul claro */
        padding: 2rem;
        border-radius: 10px;
        border: 2px solid #1F3A5F;  /* Margen azul oscuro */
    }
    .stButton button {
        background-color: #1F3A5F;  /* Botón azul oscuro */
        color: white;
        border-radius: 5px;
        padding: 0.5rem 1rem;
    }
    .stButton button:hover {
        background-color: #2E4A6F;  /* Botón azul oscuro hover */
    }
    .stTextInput input, .stNumberInput input {
        background-color: #FFFFFF;  /* Fondo blanco para inputs */
        color: #1F3A5F;  /* Texto azul oscuro */
        border-radius: 5px;
    }
    .stMarkdown h1, .stMarkdown h2, .stMarkdown h3 {
        color: #1F3A5F;  /* Títulos azul oscuro */
    }
    .stTable {
        background-color: #FFFFFF;  /* Fondo blanco para tablas */
        color: #1F3A5F;  /* Texto azul oscuro */
        border-radius: 5px;
    }
    .sidebar .sidebar-content {
        background-color: #1F3A5F;  /* Fondo azul oscuro para el menú lateral */
        color: white;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

# Logo y título
logo_url = "/content/aaaaa.png"  # Reemplaza con la URL de tu logo
st.sidebar.image(logo_url, width=100)
st.sidebar.title("BOT_IA_FINANZAS CARLOS DEVIS")

# Menú lateral
pagina = st.sidebar.radio(
    "Navegación",
    ["Registro", "Evaluación Financiera", "Plan de Inversión", "Proyección de Retiro", "Resumen"],
)

# Función para generar un PDF con el informe
def generar_pdf(usuario, analisis_financiero=None, analisis_inversion=None, analisis_retiro=None):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # Título del informe
    pdf.cell(200, 10, txt="Informe Financiero Personal", ln=True, align="C")
    pdf.ln(10)

    # Información del usuario
    pdf.cell(200, 10, txt=f"Nombre: {usuario['nombre']}", ln=True)
    pdf.cell(200, 10, txt=f"Edad: {usuario['edad']}", ln=True)
    pdf.cell(200, 10, txt=f"Email: {usuario['email']}", ln=True)
    pdf.cell(200, 10, txt=f"Teléfono: {usuario['telefono']}", ln=True)
    pdf.ln(10)

    # Análisis financiero
    if analisis_financiero:
        pdf.cell(200, 10, txt="Análisis Financiero:", ln=True)
        pdf.multi_cell(0, 10, txt=analisis_financiero)
        pdf.ln(5)

    # Análisis de inversión
    if analisis_inversion:
        pdf.cell(200, 10, txt="Análisis de Plan de Inversión:", ln=True)
        pdf.multi_cell(0, 10, txt=analisis_inversion)
        pdf.ln(5)

    # Análisis de retiro
    if analisis_retiro:
        pdf.cell(200, 10, txt="Análisis de Proyección de Retiro:", ln=True)
        pdf.multi_cell(0, 10, txt=analisis_retiro)
        pdf.ln(5)

    # Guardar el PDF
    pdf_output = "informe_financiero.pdf"
    pdf.output(pdf_output)
    return pdf_output

# Función para registrar al usuario
def registro():
    st.header("Registro de Usuario")
    nombre = st.text_input("Nombre")
    edad = st.number_input("Edad", min_value=0)
    email = st.text_input("Email")
    telefono = st.text_input("Teléfono")

    if st.button("Registrar"):
        st.session_state['usuario'] = {"nombre": nombre, "edad": edad, "email": email, "telefono": telefono}
        st.success("Usuario registrado con éxito.")

# Función para evaluar la situación financiera
def evaluacion_financiera():
    st.header("Evaluación de Situación Financiera")
    activos = st.number_input("¿Cuáles son tus activos totales? (efectivo, inversiones, propiedades, etc.): $", min_value=0.0)
    pasivos = st.number_input("¿Cuáles son tus pasivos totales? (deudas, préstamos, hipotecas, etc.): $", min_value=0.0)
    ingresos_mensuales = st.number_input("¿Cuáles son tus ingresos mensuales?: $", min_value=0.0)
    gastos_mensuales = st.number_input("¿Cuáles son tus gastos mensuales?: $", min_value=0.0)

    if st.button("Evaluar situación financiera"):
        patrimonio_neto = activos - pasivos
        flujo_efectivo_mensual = ingresos_mensuales - gastos_mensuales

        st.session_state['situacion_financiera'] = {
            "activos": activos,
            "pasivos": pasivos,
            "ingresos_mensuales": ingresos_mensuales,
            "gastos_mensuales": gastos_mensuales,
            "patrimonio_neto": patrimonio_neto,
            "flujo_efectivo_mensual": flujo_efectivo_mensual,
        }
        st.success("Evaluación financiera completada.")

# Función para evaluar el plan de inversión
def plan_inversion():
    st.header("Evaluación de Plan de Inversión")
    objetivos = st.text_input("¿Cuáles son tus objetivos de inversión? (corto, mediano, largo plazo)")
    preferencias = st.text_input("¿Cuáles son tus preferencias de inversión? (acciones, bonos, bienes raíces, etc.)")

    if st.button("Evaluar plan de inversión"):
        st.session_state['plan_inversion'] = {"objetivos": objetivos, "preferencias": preferencias}
        st.success("Plan de inversión evaluado.")

# Función para evaluar la proyección de retiro
def proyeccion_retiro():
    st.header("Evaluación de Proyección de Retiro")
    edad_actual = st.number_input("Edad actual", min_value=0)
    edad_retiro = st.number_input("Edad de retiro deseada", min_value=0)
    ingresos_retiro = st.number_input("Ingresos esperados durante el retiro (anuales): $", min_value=0.0)
    gastos_retiro = st.number_input("Gastos esperados durante el retiro (anuales): $", min_value=0.0)
    ahorros_actuales = st.number_input("Ahorros actuales para el retiro: $", min_value=0.0)
    ahorros_proyectados = st.number_input("Ahorros proyectados anuales: $", min_value=0.0)

    if st.button("Evaluar proyección de retiro"):
        st.session_state['proyeccion_retiro'] = {
            "edad_actual": edad_actual,
            "edad_retiro": edad_retiro,
            "ingresos_retiro": ingresos_retiro,
            "gastos_retiro": gastos_retiro,
            "ahorros_actuales": ahorros_actuales,
            "ahorros_proyectados": ahorros_proyectados,
        }
        st.success("Proyección de retiro evaluada.")

# Función para mostrar el resumen
def resumen():
    st.header("Resumen de Análisis Financiero")
    st.write(f"**Usuario:** {st.session_state['usuario']['nombre']}")

    if 'situacion_financiera' in st.session_state:
        st.subheader("Situación Financiera")
        st.table({
            "Activos": [f"${st.session_state['situacion_financiera']['activos']:.2f}"],
            "Pasivos": [f"${st.session_state['situacion_financiera']['pasivos']:.2f}"],
            "Patrimonio Neto": [f"${st.session_state['situacion_financiera']['patrimonio_neto']:.2f}"],
            "Flujo de Efectivo Mensual": [f"${st.session_state['situacion_financiera']['flujo_efectivo_mensual']:.2f}"],
        })

    if 'plan_inversion' in st.session_state:
        st.subheader("Plan de Inversión")
        st.table({
            "Objetivos": [st.session_state['plan_inversion']['objetivos']],
            "Preferencias": [st.session_state['plan_inversion']['preferencias']],
        })

    if 'proyeccion_retiro' in st.session_state:
        st.subheader("Proyección de Retiro")
        st.table({
            "Edad Actual": [st.session_state['proyeccion_retiro']['edad_actual']],
            "Edad de Retiro": [st.session_state['proyeccion_retiro']['edad_retiro']],
            "Ingresos Esperados": [f"${st.session_state['proyeccion_retiro']['ingresos_retiro']:.2f}"],
            "Gastos Esperados": [f"${st.session_state['proyeccion_retiro']['gastos_retiro']:.2f}"],
            "Ahorros Actuales": [f"${st.session_state['proyeccion_retiro']['ahorros_actuales']:.2f}"],
            "Ahorros Proyectados": [f"${st.session_state['proyeccion_retiro']['ahorros_proyectados']:.2f}"],
        })

    if st.button("Descargar Informe en PDF"):
        pdf_path = generar_pdf(
            st.session_state['usuario'],
            st.session_state.get('analisis_financiero'),
            st.session_state.get('analisis_inversion'),
            st.session_state.get('analisis_retiro')
        )
        with open(pdf_path, "rb") as file:
            st.download_button(
                label="Descargar PDF",
                data=file,
                file_name="informe_financiero.pdf",
                mime="application/pdf"
            )

    if st.button("Salir"):
        st.session_state.clear()
        st.experimental_rerun()

# Función principal
def main():
    if pagina == "Registro":
        registro()
    elif pagina == "Evaluación Financiera":
        evaluacion_financiera()
    elif pagina == "Plan de Inversión":
        plan_inversion()
    elif pagina == "Proyección de Retiro":
        proyeccion_retiro()
    elif pagina == "Resumen":
        resumen()

if __name__ == "__main__":
    main()