# -*- coding: utf-8 -*-
"""Pruebfinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-q5KfMGUxd9BVdaxYOgAWvJ31NzX_1S4
"""

import streamlit as st
import os
from sklearn import metrics
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from openai import OpenAI
from fpdf import FPDF  # Biblioteca para generar PDFs

# Inicializar el cliente de OpenAI
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# Función para generar un PDF con el informe
def generar_pdf(usuario, analisis_financiero=None, analisis_inversion=None, analisis_retiro=None):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # Título del informe
    pdf.cell(200, 10, txt="Informe Financiero Personal", ln=True, align="C")
    pdf.ln(10)

    # Información del usuario
    pdf.cell(200, 10, txt=f"Nombre: {usuario['nombre']}", ln=True)
    pdf.cell(200, 10, txt=f"Edad: {usuario['edad']}", ln=True)
    pdf.cell(200, 10, txt=f"Email: {usuario['email']}", ln=True)
    pdf.cell(200, 10, txt=f"Teléfono: {usuario['telefono']}", ln=True)
    pdf.ln(10)

    # Análisis financiero
    if analisis_financiero:
        pdf.cell(200, 10, txt="Análisis Financiero:", ln=True)
        pdf.multi_cell(0, 10, txt=analisis_financiero)
        pdf.ln(5)

    # Análisis de inversión
    if analisis_inversion:
        pdf.cell(200, 10, txt="Análisis de Plan de Inversión:", ln=True)
        pdf.multi_cell(0, 10, txt=analisis_inversion)
        pdf.ln(5)

    # Análisis de retiro
    if analisis_retiro:
        pdf.cell(200, 10, txt="Análisis de Proyección de Retiro:", ln=True)
        pdf.multi_cell(0, 10, txt=analisis_retiro)
        pdf.ln(5)

    # Guardar el PDF
    pdf_output = "informe_financiero.pdf"
    pdf.output(pdf_output)
    return pdf_output

# Función para registrar al usuario
def registrar_usuario():
    st.write("\n¡Bienvenido al Bot de Finanzas Personales De Carlos Devis!")
    nombre = st.text_input("Nombre")
    edad = st.number_input("Edad", min_value=0)
    email = st.text_input("Email")
    telefono = st.text_input("Teléfono")

    if st.button("Registrar"):
        st.session_state['usuario'] = {"nombre": nombre, "edad": edad, "email": email, "telefono": telefono}
        st.write("\nUsuario registrado con éxito.")

# Función para evaluar la situación financiera
def evaluar_situacion_financiera():
    st.write("\nPor favor, ingresa tus datos financieros en dólares ($):")
    activos = st.number_input("¿Cuáles son tus activos totales? (efectivo, inversiones, propiedades, etc.): $", min_value=0.0)
    pasivos = st.number_input("¿Cuáles son tus pasivos totales? (deudas, préstamos, hipotecas, etc.): $", min_value=0.0)
    ingresos_mensuales = st.number_input("¿Cuáles son tus ingresos mensuales?: $", min_value=0.0)
    gastos_mensuales = st.number_input("¿Cuáles son tus gastos mensuales?: $", min_value=0.0)

    if st.button("Evaluar situación financiera"):
        patrimonio_neto = activos - pasivos
        flujo_efectivo_mensual = ingresos_mensuales - gastos_mensuales

        st.write(f"\nPatrimonio Neto: ${patrimonio_neto:.2f}")
        st.write(f"Flujo de Efectivo Mensual: ${flujo_efectivo_mensual:.2f}")

        st.session_state['situacion_financiera'] = {"activos": activos, "pasivos": pasivos, "ingresos_mensuales": ingresos_mensuales, "gastos_mensuales": gastos_mensuales}

# Función para evaluar el plan de inversión
def evaluar_plan_inversion():
    st.write("\nPor favor, ingresa tus datos de inversión:")
    objetivos = st.text_input("¿Cuáles son tus objetivos de inversión? (corto, mediano, largo plazo)")
    preferencias = st.text_input("¿Cuáles son tus preferencias de inversión? (acciones, bonos, bienes raíces, etc.)")

    if st.button("Evaluar plan de inversión"):
        st.session_state['plan_inversion'] = {"objetivos": objetivos, "preferencias": preferencias}

# Función para evaluar la proyección de retiro
def evaluar_proyeccion_retiro():
    st.write("\nPor favor, ingresa tus datos de retiro en dólares ($):")
    edad_actual = st.number_input("Edad actual", min_value=0)
    edad_retiro = st.number_input("Edad de retiro deseada", min_value=0)
    ingresos_retiro = st.number_input("Ingresos esperados durante el retiro (anuales): $", min_value=0.0)
    gastos_retiro = st.number_input("Gastos esperados durante el retiro (anuales): $", min_value=0.0)
    ahorros_actuales = st.number_input("Ahorros actuales para el retiro: $", min_value=0.0)
    ahorros_proyectados = st.number_input("Ahorros proyectados anuales: $", min_value=0.0)

    if st.button("Evaluar proyección de retiro"):
        st.session_state['proyeccion_retiro'] = {"edad_actual": edad_actual, "edad_retiro": edad_retiro, "ingresos_retiro": ingresos_retiro, "gastos_retiro": gastos_retiro, "ahorros_actuales": ahorros_actuales, "ahorros_proyectados": ahorros_proyectados}

# Función para analizar con OpenAI
def analizar_con_openai(prompt):
    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "Eres un analista financiero experto. Analiza la información proporcionada y proporciona recomendaciones claras y detalladas."},
                {"role": "user", "content": prompt}
            ]
        )
        return response.choices[0].message.content
    except Exception as e:
        st.error(f"Error al conectar con OpenAI: {e}")
        return None

# Función principal
def main():
    if 'usuario' not in st.session_state:
        registrar_usuario()
    else:
        st.write(f"Bienvenido de nuevo, {st.session_state['usuario']['nombre']}")

        # Evaluar situación financiera
        if st.checkbox("¿Deseas evaluar tu situación financiera?"):
            evaluar_situacion_financiera()
            if 'situacion_financiera' in st.session_state:
                prompt = f"El usuario tiene los siguientes datos financieros: Activos: ${st.session_state['situacion_financiera']['activos']:.2f}, Pasivos: ${st.session_state['situacion_financiera']['pasivos']:.2f}, Ingresos Mensuales: ${st.session_state['situacion_financiera']['ingresos_mensuales']:.2f}, Gastos Mensuales: ${st.session_state['situacion_financiera']['gastos_mensuales']:.2f}. Analiza su situación financiera y proporciona recomendaciones."
                st.session_state['analisis_financiero'] = analizar_con_openai(prompt)

        # Evaluar plan de inversión
        if st.checkbox("¿Deseas evaluar tu plan de inversión?"):
            evaluar_plan_inversion()
            if 'plan_inversion' in st.session_state:
                prompt = f"El usuario tiene los siguientes objetivos de inversión: {st.session_state['plan_inversion']['objetivos']} y prefiere invertir en: {st.session_state['plan_inversion']['preferencias']}. Analiza su plan de inversión y proporciona recomendaciones."
                st.session_state['analisis_inversion'] = analizar_con_openai(prompt)

        # Evaluar proyección de retiro
        if st.checkbox("¿Deseas evaluar tu proyección de retiro?"):
            evaluar_proyeccion_retiro()
            if 'proyeccion_retiro' in st.session_state:
                prompt = f"El usuario tiene los siguientes datos de retiro: Edad Actual: {st.session_state['proyeccion_retiro']['edad_actual']}, Edad de Retiro Deseada: {st.session_state['proyeccion_retiro']['edad_retiro']}, Ingresos Esperados durante el Retiro: ${st.session_state['proyeccion_retiro']['ingresos_retiro']:.2f}, Gastos Esperados durante el Retiro: ${st.session_state['proyeccion_retiro']['gastos_retiro']:.2f}, Ahorros Actuales: ${st.session_state['proyeccion_retiro']['ahorros_actuales']:.2f}, Ahorros Proyectados Anuales: ${st.session_state['proyeccion_retiro']['ahorros_proyectados']:.2f}. Analiza su proyección de retiro y proporciona recomendaciones."
                st.session_state['analisis_retiro'] = analizar_con_openai(prompt)

        # Resumen final
        st.write("\nResumen de tu análisis financiero:")
        st.write(f"Usuario: {st.session_state['usuario']}")
        if 'analisis_financiero' in st.session_state:
            st.write("\nAnálisis Financiero:")
            st.write(st.session_state['analisis_financiero'])
        if 'analisis_inversion' in st.session_state:
            st.write("\nAnálisis de Plan de Inversión:")
            st.write(st.session_state['analisis_inversion'])
        if 'analisis_retiro' in st.session_state:
            st.write("\nAnálisis de Proyección de Retiro:")
            st.write(st.session_state['analisis_retiro'])

        # Botón para descargar el informe en PDF
        if st.button("Descargar Informe en PDF"):
            pdf_path = generar_pdf(
                st.session_state['usuario'],
                st.session_state.get('analisis_financiero'),
                st.session_state.get('analisis_inversion'),
                st.session_state.get('analisis_retiro')
            )
            with open(pdf_path, "rb") as file:
                st.download_button(
                    label="Descargar PDF",
                    data=file,
                    file_name="informe_financiero.pdf",
                    mime="application/pdf"
                )

if __name__ == "__main__":
    main()